name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  id-token: write  # Add this line to grant permission for ID token

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build the project
        run: npm install && npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: build  # or the folder where your build files are located
